apiVersion: v1
kind: Service
metadata:
  name: flight-delay-svc
  labels:
    app: flight-delay
spec:
  type: NodePort
  selector:
    app: flight-delay
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080


