apiVersion: v1
kind: Service
metadata:
  name: flight-delay-svc
spec:
  type: NodePort
  selector:
    app: flight-delay
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
