apiVersion: v1
kind: Service
metadata:
  name: personality-api-service
  labels:
    app: personality-api
    service: api
spec:
  type: NodePort
  selector:
    app: personality-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080  # Будет доступно на http://minikube-ip:30080
  sessionAffinity: ClientIP