apiVersion: v1
kind: Service
metadata:
  name: durak-rl-api
spec:
  type: NodePort
  selector:
    app: durak-rl-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007  # Можно указать, либо оставить Kubernetes выбрать случайный
