version: "3.8"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile

    image: custom-airflow:latest
    restart: always

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor

    volumes:
      - ./dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../models:/opt/airflow/models
      - ../reports:/opt/airflow/reports
      - ../data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt

    ports:
      - "8080:8080"

    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname a --lastname a --role Admin --email a@a.com || true &&
               airflow webserver & airflow scheduler"